name: flutter_gpiod
description:
  Dart package for accessing GPIO using the GPIO character device interface on linux.
  Supports signal edge listening, active state, open source/drain and (if supported by platform) bias.
version: 0.2.0
homepage: https://ardera.dev/
repository: https://github.com/ardera/flutter_gpiod
   
environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  ffi: ^0.1.3
  tuple: ^1.0.3
  path: ^1.7.0